/* main.c — Ring app entry point for the Android WebView example.
 *
 * Owns ALL Ring loading. The backend (ring_webview_android.c) keeps only
 * JNI; its worker thread calls ring_app_main() and never touches Ring
 * loading directly.
 *
 * Two responsibilities:
 *
 *   1. ring_vm_extension() — replicates Ring's ext.c verbatim and appends
 *      the webview backend's ringlib_init() so the webview_* functions are
 *      registered when the VM starts. This file replaces ext.c in the Ring
 *      source list (see CMakeLists.txt), keeping Ring sources pristine.
 *
 *   2. ring_app_main() — creates the Ring state and runs the embedded
 *      bytecode from ringappcode.c (generated by `ring -geo -norun
 *      main.ring`, which compiles main.ring and every transitive load into
 *      one self-contained bytecode — no .ring files are read at runtime).
 */

#include "ring.h"
#include "ringappcode.h"

/* Provided by ring_webview_android.c */
extern void ringlib_init(RingState *pRingState);

/* ------------------------------------------------------------------ */
/* 1. Ring VM extension hook (replaces ext.c)                          */
/* ------------------------------------------------------------------ */

void ring_vm_extension(RingState *pRingState) {
/* List */
#if RING_VM_LISTFUNCS
	ring_vm_list_loadfunctions(pRingState);
#endif
/* Math */
#if RING_VM_MATH
	ring_vm_math_loadfunctions(pRingState);
#endif
/* File */
#if RING_VM_FILE
	ring_vm_file_loadfunctions(pRingState);
#endif
/* OS */
#if RING_VM_OS
	ring_vm_os_loadfunctions(pRingState);
#endif
/* DLL */
#if RING_VM_DLL
	ring_vm_dll_loadfunctions(pRingState);
#endif
/* Reflection and Meta-programming */
#if RING_VM_REFMETA
	ring_vm_refmeta_loadfunctions(pRingState);
#endif
/* VM Information */
#if RING_VM_INFO
	ring_vm_info_loadfunctions(pRingState);
#endif
/* WebView backend */
	ringlib_init(pRingState);
}

/* ------------------------------------------------------------------ */
/* 2. App entry point — called by the backend's worker thread          */
/* ------------------------------------------------------------------ */

/* Creates the Ring state and runs the embedded bytecode. Returns only
 * when the Ring program exits (i.e. webview_run() returns and main()
 * finishes). The backend captures the live RingState itself inside
 * ring_webview_create() via RING_API_STATE, so no state is passed back. */
void ring_app_main(void) {
	RingState *pRingState = ring_state_new();
	if (!pRingState) {
		return;
	}
	pRingState->lRun = 1;
	ringappcode_run(pRingState);
	ring_state_delete(pRingState);
}
